### ISSUE TITLE
Feedback for RunTipi Dashboard

### ISSUE THREAD

**Issue by marcoprd** [runtipi/runtipi-docs#10]
Hello, I've installed the application using the curl comand on an ubuntu server 22.04 machine, and when I try to access the dashboard via the IP address indicated in the runtipi CLI I briefly see the password creation screen but then the page crashes with the error "Application error: a client-side exception has occurred (see the browser console for more information). The browser console has the following output:

﻿
_next/static/chunks/…8d5887e271eab9.js:1 
 Failed to load resource: the server responded with a status of 502 (Bad Gateway)
_next/image?url=%2Ftipi.png&w=64&q=75:1 
 Failed to load resource: the server responded with a status of 502 (Bad Gateway)
_next/static/chunks/…6bf2e34ff3ca8d.js:1 
 Failed to load resource: the server responded with a status of 502 (Bad Gateway)
874-eb73f74a431b60a1.js:1 ChunkLoadError: Loading chunk 566 failed.
(error: http://192.168.0.18/_next/static/chunks/app/(auth)/register/page-c78d5887e271eab9.js)
    at __webpack_require__.f.j (webpack-b4a24a37e184292e.js:1:3964)
    at webpack-b4a24a37e184292e.js:1:1691
    at Array.reduce (<anonymous>)
    at __webpack_require__.e (webpack-b4a24a37e184292e.js:1:1639)
    at 874-eb73f74a431b60a1.js:17:7024
    at 874-eb73f74a431b60a1.js:17:7226
    at 874-eb73f74a431b60a1.js:17:7429
    at c (874-eb73f74a431b60a1.js:17:8975)
7262a124-3f7393651029acd5.js:9 Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at rx (7262a124-3f7393651029acd5.js:9:117545)
    at Lk (7262a124-3f7393651029acd5.js:9:94308)
    at 7262a124-3f7393651029acd5.js:9:94130
    at bf (7262a124-3f7393651029acd5.js:9:94137)
    at cf (7262a124-3f7393651029acd5.js:9:91782)
    at mf (7262a124-3f7393651029acd5.js:9:91218)
    at MessagePort.P (874-eb73f74a431b60a1.js:25:1665)

**Comment by meienberger** [comment]
Hello @marcoprd, is there something in `runtipi/logs/error.log`? Also, what are the specs of your server? This issue happened to other users on very low end devices
