### ISSUE TITLE
Tipi running but inaccessible`

### ISSUE THREAD

**Issue by IMJONEZZ** [runtipi/runtipi-docs#18]
I've tried this on 2 different devices now, both running Ubuntu LTS.

Steps to reproduce:
- Run the curl | bash command to install tipi
- "Tipi successfully Started, Visit localhost:80 to access the dashboard"
- Go to address
- "Unable to connect, Taking too long to respond"

**Comment by IMJONEZZ** [comment]
Specs:
i9 cpu
3080 gpu
64GB RAM
It's not a low end system problem

**Comment by meienberger** [comment]
Hello @IMJONEZZ we have fixed this bug in the latest version and everything should now work correctly
