### ISSUE TITLE
Ubuntu 22.04 Installation script piped to bash not working w/o sudo

### ISSUE THREAD

**Issue by falkheiland** [runtipi/runtipi-docs#19]
I followed the instructions on https://runtipi.io/docs/getting-started/installation

and ended up with no running containers. after i rerun the mentioned line:

https://github.com/runtipi/runtipi-docs/blob/f32f2ccc9688e394fa12d574e7521a365b069435/pages/docs/getting-started/installation.mdx#L61

with the addition of `sudo`
```
curl -L https://raw.githubusercontent.com/runtipi/runtipi/master/scripts/install.sh | sudo bash
```

the installation was successful.

**Comment by meienberger** [comment]
Hello @falkheiland we have fixed the issue and it should now be working as expected
