### ISSUE TITLE
Feedback for “Installation”

### ISSUE THREAD

**Issue by orneo1212** [runtipi/runtipi-docs#21]
Does not work on debian variant - SparkyLinux.

**Comment by steveiliop56** [comment]
Hello @orneo1212,

Unfortunately by not providing any logs of the installation we can neither help you solve the problem nor fix it. Please provide some logs/screenshots of the installation process you followed or join the discord server. The docs repository is not the right place to solve your issue.

**Comment by steveiliop56** [comment]
No response
