### ISSUE TITLE
Installation problem for Linux Mint

### ISSUE THREAD

**Issue by jirsay** [runtipi/runtipi-docs#29]
I know, I know, it's not a server distribution.
However...
Error returned is:
root@T430:~# curl -L https://setup.runtipi.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   169  100   169    0     0    217      0 --:--:-- --:--:-- --:--:--   218
100  7362  100  7362    0     0   7421      0 --:--:-- --:--:-- --:--:-- 36994
Installing runtipi...
cat: /etc/upstream-release: Is a directory
Thanks!

**Comment by meienberger** [comment]
Mint is not officially supported or tested. Please try to install docker manually before running the install script
