### ISSUE TITLE
Feedback for “Folder Structure”

### ISSUE THREAD

**Issue by ag14spirit** [runtipi/runtipi-docs#31]
When referencing the [Runtipi Docs about folder structures](https://runtipi.io/docs/reference/folder-structure) to further customize my Traefik config, I noticed that the published directory structure:

```
apps
app-data
logs
media
repos
state
```

...doesn't match the functional directory structure of my Runtipi install:

```
VERSION
app-data
apps
backups
data
logs
media
repos
runtipi-cli
scripts
state
traefik
user-config
```

I'm doing my best to come up to speed on Runtipi's architecture. If I can figure it out well enough, I'll be sure to open pull requests for clarified documentation!

**Comment by steveiliop56** [comment]
Fixed in https://github.com/runtipi/runtipi-docs/pull/40
