### ISSUE TITLE
Appsmith will be a great addition as a no-code app builder

### ISSUE THREAD

**Issue by edouardflowasia** [runtipi/runtipi-docs#32]
Hey Runtipi Team,

I noticed Runtipi appstore is missing a no-code app builder. I stumbled upon Appsmith ([appsmith.com](https://www.appsmith.com/)) and thought it could be a great addition. Just to clarify, I'm not affiliated with Appsmith in any way; I just believe it could complement the appstore nicely.

Thanks for considering!

**Comment by steveiliop56** [comment]
Hello,

Please open a discussion on our appstore repo. Thank you!
